FROM golang:alpine
LABEL maintainer="lgaete.astudillo@gmail.com"

RUN apk add --no-cache --virtual make
RUN apk add --no-cache --virtual git 
RUN apk add --no-cache --virtual bash
RUN apk add --no-cache --virtual openssl